dependencies:
- base
- vector
# - liquid-prelude
# # - liquid-ghc-prim
# - liquid-containers
# - liquid-vector
# - liquidhaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-imports
- -Wno-unused-top-binds
# - -fplugin=LiquidHaskell

library:
  source-dirs:
    - src